### ISSUE TITLE
Obey max length

### ISSUE THREAD

**Issue by glacials** [MilkmanWes/WoW-Guild-Name-Check#21]
In the [Guild Name Change tool][1] it looks like there's a max length of 24 characters in guild names, but this tool incorrectly lists names with > 24 characters as available.

[1]: https://us.shop.battle.net/en-us/product/world-of-warcraft-service-guild-services

**Comment by MilkmanWes** [comment]
Originally set max length to 32 (really not sure where I got that number...). changed the max length check and changes live in last push #22
